{% set name = "partd" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/partd-{{ version }}.tar.gz
  sha256: d022c33afbdc8405c226621b015e8067888173d85f7f5ecebb3cafed9a20f02c
  # patches:                           # [py==312]
  #   - patches/0000-3.12-compat.patch # [py==312]

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - versioneer 0.29
  run:
    - python
    - locket
    - toolz
  run_constrained:
    - numpy >= 1.20.0
    - pandas >=1.3.0

test:
  imports:
    - partd
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/partd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Appendable key-value storage
  description: |
    Partd stores key-value pairs. Values are raw bytes. It excels at shuffling
    operations.
  doc_url: https://pypi.org/pypi/partd/
  dev_url: https://github.com/dask/partd

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
