{% set version = "1.0.0" %}

package:
  name: partd
  version: {{ version }}

source:
  fn: partd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: 54fd91bc3b9c38159c790cd16950dbca6b019a2ead4c51dee4f9efc884f8ce0e

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - locket
    - toolz

  run:
    - python
    - locket
    - toolz

test:
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Data structure for on-disk shuffle operations
  description: |
    Partd stores key-value pairs. Values are raw bytes. It excels at shuffling
    operations.
  doc_url: https://pypi.python.org/pypi/partd/
  doc_source_url: https://github.com/dask/partd/blob/master/README.rst
  dev_url: https://github.com/dask/partd

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
