{% set name = "partd" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/partd-{{ version }}.tar.gz
  sha256: 56c25dd49e6fea5727e731203c466c6e092f308d8f0024e199d02f6aa2167f67
  patches:                           # [py==312]
    - patches/0000-3.12-compat.patch # [py==312]

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv

requirements:
  build:
    - patch     # [unix and py==312]
    - m2-patch  # [win and py==312]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - locket
    - toolz
  run_constrained:
    - numpy >= 1.9.0
    - pandas >=0.19.0

test:
  imports:
    - partd
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/partd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Appendable key-value storage
  description: |
    Partd stores key-value pairs. Values are raw bytes. It excels at shuffling
    operations.
  doc_url: https://pypi.org/pypi/partd/
  dev_url: https://github.com/dask/partd

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
