{% set name = "partd" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/partd-{{ version }}.tar.gz
  sha256: aa0ff35dbbcc807ae374db56332f4c1b39b46f67bf2975f5151e0b4186aed0d5

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - locket
    - toolz
  run_constrained:
    - numpy >= 1.9.0
    - pandas >=0.19.0

test:
  imports:
    - partd
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/partd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Appendable key-value storage
  description: |
    Partd stores key-value pairs. Values are raw bytes. It excels at shuffling
    operations.
  doc_url: https://pypi.org/pypi/partd/
  dev_url: https://github.com/dask/partd

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
