travis:
  secure:
    BINSTAR_TOKEN: U0EkHl46UJXBUK+4Gw3bua9IsKix8mkFEypvE16cdcIIsIoKg/Q8gUKX7c1+60zdq7kAvNn7SoCX+7Wmk1TKcrn3ao5WHSkptGoK4Di/Xn+Awj6fIDIIoHaSczr94pcBnZ2B8kkTpgXZOk4qeVFQyGjpyG8ADqz5xn/RUv9SywOIZbQkjPtTNR6AQIpxAy+lcKSPcTCAt0X0f4L8LRZK0VdEU/kbgIYdaRn+ejioBx0z3XVO9noR/uWxXeHuzRIM1q97XSssl3Zza5BvRjdKXyskOE4iuIfTC38wcjSXz5ZKVDbXX5cISONV5CJP1BJF+eIoUJtyha7AHL5IOuYW7L+IG7PcJvloCtPtG7Thy8LzoodZwVKtHE2Bmi2xNNlG9R8o5FDqrkeSk8bLDQ6AJe1szvLVv/FARbnhWkKPAU+g/A9RTfA5fJMBv0SEzDAc809vS6VQAVoaFBOTDIgkGKF++S4HC8SoDzDdzdacM4D08A7WzjXHT1lJR6PiJSMwSN3D8CEt8A6b1xXhsS00DR7nO/+YXGB71vLTnCX3WPvaIhtP1gM8PQUBHGyTGSt9Ya+umCxyOjbfYxKA9EYagw45bM93O5F2lZ2SIovaPpVk1v7lhVQ59Qas8aYaAfUKQtuxaxSXbLboJwyrzewXM8TQVodRUW0RT8+Ajihpad0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
