travis:
  secure:
    BINSTAR_TOKEN: keIzOjvAVIQATb+1DQgDmah0gF0UYXXPyPuITck5WHugzYnAyMSisH7l5l0wj6WgZrHRBO1q49jH8p1ywDcwLddM6Jvk2ko3YvvLLLRga2O0o9CRLaDO8W5NeWi4tU57CHfA9fmS/9zdn6zSdksWMd8CNwoyqBW+06CX5hptcXiDcpgmdYXCx6azTE+BpRzqSGyHnUqwkyiIxf/cSLtuoRT481k/6FnoFxjRk9Vv9U9OoPVaNT8xexpSaE9kXUNxyzTvScKA19qbYlRA11ip7XMfCn57Gqd3I38q+Jmbh7TdDsaoFlAvgDyFogyqNJIy8FiiAlgk1gutl1BvzPXyP+tlu2XhXIsgSFVZZrnbjNJhbvk7krEwqgX5V/XIrSwEcfRg70mw5WX2EwiWnaDvvutuPAGj12C2lvOq/R2we+2Lfhrml8lUpkEBO0pE5egFy7KvEpX2/nV+PqF+8gdLRqxsONelFgnGW2ByiP3mxEAVtQ7sfpy6qEx9SySIBjRTZUFndcL4DqcN4isI/LH84FhsY/yeRQIycYuhJGfrJwOwoay8iiVJFs0fmKL/edKD4fUTlRCwKJx4aK6pB3v6UZY+DO4UyZfCtnWTHpXL4hRbcyjzoZlUV5N0iP7TE+uJWC/1N/pBudXA/9kvlMwe4b03DiB91aZHbYsAXhm/8j0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
