travis:
  secure:
    BINSTAR_TOKEN: jD7kWOJxffC6asuS7XTwtSblNl+qyyCGCaxs/6BhYa3Z/6dgByW7ldplV9tVS/DCOLnTBRm46dreSGGAs7L+w2c/AXXw+qgyrSBQRi/bLDVxfyQAO4h33DKPomZZh5MSJZpodmQpGs1FhCpPSxjxA7lRwHub3u1+6qxa4WZtZ3LXz/24GODoE2y7GUiODRDVsXW1zAPjjggtuJiAV5wgE8K1KcGGPitoY5faoA0cytmYPlgyYIISqMZRh5xWk+xzXcSPpKIKqkXpQgdngDfah2Pp6wOZ05Cd4R+qAwnX258GmYS2Vqd6V25eRvIfFBijq03mwMEeQBxhv9ZIazw9Al4TBkIcO7QvBY56JeTR77hngOlebYD8+7ee0xLOp47R3TnoWiNYQbDt4awUyWSXo5CWW/gOqIl6CrfWzhQwpvXhWZrRHT1jcFeCC8p+jXi+7YN1l0qwICM6NGOPqkpk/rR0Rc6S3uSiPlR4KxybF/YRadSh4veWmx2HOp+e6BWOroTr8d5+/zpQWLz+k8pgGhafEHCOyLwBb0JsadTji2HYmYMwpHEdNW96bqA/HRfNhe2Kx/LBPTaSpaLuVBzOdU3duZnkhfxyV1DMwy/H9MVO0qpVb5pQpHO78J6HLp9/1+DC6DLjCPX+vfiIZvIJuDb6igs2H+3CbQF/ysOJgoE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
